# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 326c0c3260ef8d8356360a79a5091d30e12e2307c321f8f1010485dcee8a0111f6e4ba29bbbe27957b58c9da13bf96b5135514bd4e2a5e97b5bfc427ba6ea6cd

test:
  secret_key_base: a499338e99f2187f680cf0f41c56112767f61ff2fa3000a756d3ed3f11c2ce7771e7e07d80ba8fe2a6b4a32d03a9541b17debec19d1b63d236630b4dcfe08f08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
